version: '3'

services:
  sirbot-pythondev:
    image: pyslackers/sirbot-pythondev:master
    container_name: sirbot-pythondev
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../config:/etc/sirbot

  ngrok:
    image: wernight/ngrok
    container_name: sirbot-ngrok
    links:
      - sirbot-pythondev
    ports:
      - 0.0.0.0:8000:4040
    env_file:
      - .env
    environment:
     - NGROK_PORT=sirbot:8080
    restart: unless-stopped
